#!/bin/bash

cargo -Z unstable-options build --bins --release --artifact-dir "./content/releases/$(rustc --print host-tuple)/$(cargo metadata --no-deps | jq -r '.packages[0].version' | tr -d '\n')" && echo "Building site with release via cargo run..." && sleep 3 && cargo run
